package GUI;

import CITY.City;

import javax.swing.*;

public class GameUI {

    private JPanel MainPanel;
    private JPanel Board;
    private JLabel lbPStreet39;
    private JLabel lbNStreet39;
    private JLabel lbPStreet38;
    private JLabel lbNStreet38;
    private JLabel lbPStreet37;
    private JLabel lbNStreet37;
    private JLabel lbNStreet35;
    private JLabel lbPStreet35;
    private JLabel lbPStreet34;
    private JLabel lbNStreet34;
    private JLabel lbPStreet32;
    private JLabel lbNStreet32;
    private JLabel lbPStreet31;
    private JLabel lbNStreet31;
    private JLabel lbNStreet29;
    private JLabel lbPStreet29;
    private JLabel lbNStreet28;
    private JLabel lbPStreet28;
    private JLabel lbNStreet27;
    private JLabel lbPStreet27;
    private JLabel lbNStreet26;
    private JLabel lbPStreet26;
    private JLabel lbNStreet25;
    private JLabel lbPStreet25;
    private JLabel lbNStreet24;
    private JLabel lbPStreet24;
    private JLabel lbNStreet23;
    private JLabel lbPStreet23;
    private JLabel lbNStreet21;
    private JLabel lbPStreet21;
    private JLabel lbPStreet19;
    private JLabel lbNStreet19;
    private JLabel lbNStreet18;
    private JLabel lbPStreet18;
    private JLabel lbNStreet16;
    private JLabel lbPStreet16;
    private JLabel lbNStreet15;
    private JLabel lbPStreet15;
    private JLabel lbNStreet14;
    private JLabel lbPStreet14;
    private JLabel lbNStreet13;
    private JLabel lbPStreet13;
    private JLabel lbNStreet12;
    private JLabel lbPStreet12;
    private JLabel lbNStreet11;
    private JLabel lbPStreet11;
    private JLabel lbNStreet9;
    private JLabel lbPStreet9;
    private JLabel lbNStreet8;
    private JLabel lbPStreet8;
    private JLabel lbNStreet6;
    private JLabel lbPStreet6;
    private JLabel lbNStreet5;
    private JLabel lbPStreet5;
    private JLabel lbNStreet4;
    private JLabel lbPStreet4;
    private JLabel lbNStreet3;
    private JLabel lbPStreet3;
    private JLabel lbNStreet1;
    private JLabel lbPStreet1;


    public JPanel init(){
        lbNStreet1.setText(City.field[1].getName());
        lbPStreet1.setText(City.field[1].getPrize());
        lbNStreet3.setText(City.field[3].getName());
        lbPStreet3.setText(City.field[3].getPrize());
        lbNStreet4.setText(City.field[4].getName());
        lbPStreet4.setText(City.field[4].getPrize());
        lbNStreet5.setText(City.field[5].getName());
        lbPStreet5.setText(City.field[5].getPrize());
        lbNStreet6.setText(City.field[6].getName());
        lbPStreet6.setText(City.field[6].getPrize());
        lbNStreet8.setText(City.field[8].getName());
        lbPStreet8.setText(City.field[8].getPrize());
        lbNStreet9.setText(City.field[9].getName());
        lbPStreet9.setText(City.field[9].getPrize());
        lbNStreet11.setText(City.field[11].getName());
        lbPStreet11.setText(City.field[11].getPrize());
        lbNStreet12.setText(City.field[12].getName());
        lbPStreet12.setText(City.field[12].getPrize());
        lbNStreet13.setText(City.field[13].getName());
        lbPStreet13.setText(City.field[13].getPrize());
        lbNStreet14.setText(City.field[14].getName());
        lbPStreet14.setText(City.field[14].getPrize());
        lbNStreet15.setText(City.field[15].getName());
        lbPStreet15.setText(City.field[15].getPrize());
        lbNStreet16.setText(City.field[16].getName());
        lbPStreet16.setText(City.field[16].getPrize());
        lbNStreet18.setText(City.field[18].getName());
        lbPStreet18.setText(City.field[18].getPrize());
        lbNStreet19.setText(City.field[19].getName());
        lbPStreet19.setText(City.field[19].getPrize());
        lbNStreet21.setText(City.field[21].getName());
        lbPStreet21.setText(City.field[21].getPrize());
        lbNStreet23.setText(City.field[23].getName());
        lbPStreet23.setText(City.field[23].getPrize());
        lbNStreet24.setText(City.field[24].getName());
        lbPStreet24.setText(City.field[24].getPrize());
        lbNStreet25.setText(City.field[25].getName());
        lbPStreet25.setText(City.field[25].getPrize());
        lbNStreet26.setText(City.field[26].getName());
        lbPStreet26.setText(City.field[26].getPrize());
        lbNStreet27.setText(City.field[27].getName());
        lbPStreet27.setText(City.field[27].getPrize());
        lbNStreet28.setText(City.field[28].getName());
        lbPStreet28.setText(City.field[28].getPrize());
        lbNStreet29.setText(City.field[29].getName());
        lbPStreet29.setText(City.field[29].getPrize());
        lbNStreet31.setText(City.field[31].getName());
        lbPStreet31.setText(City.field[31].getPrize());
        lbNStreet32.setText(City.field[32].getName());
        lbPStreet32.setText(City.field[32].getPrize());
        lbNStreet34.setText(City.field[34].getName());
        lbPStreet34.setText(City.field[34].getPrize());
        lbNStreet35.setText(City.field[35].getName());
        lbPStreet35.setText(City.field[35].getPrize());
        lbNStreet37.setText(City.field[37].getName());
        lbPStreet37.setText(City.field[37].getPrize());
        lbNStreet38.setText(City.field[38].getName());
        lbPStreet38.setText(City.field[38].getPrize());
        lbNStreet39.setText(City.field[39].getName());
        lbPStreet39.setText(City.field[39].getPrize());

        return MainPanel;
    }
}
